export const navData = [
  ["Editorial", "Following"],
  [
    "Sustainability",
    "Wallpapers",
    "COVID-19",
    "Travel",
    "Nature",
    "Textures & Patterns",
    "Current Events",
    "People",
    "Business & Work",
    "Technology",
    "Animals",
    "Interiors",
    "Architecture",
    "Food & Drink",
    "Athletics",
    "Spirituality",
    "Health & Wellness",
    "Film",
    "Fasion",
    "Experimental",
    "Arts & Culture",
    "History",
  ],
  ["view all"],
];
